# This workflow will build a PyOxidizer binary for Mac OS when a tag is pushed

name: Build OSX binary

env:
  PYOXIDIZER_DOWNLOAD: https://github.com/indygreg/PyOxidizer/releases/download/pyoxidizer%2F0.18.0/pyoxidizer-0.18.0-macos-universal.zip

on:
  workflow_dispatch: {}
  push:
    tags:
      - '*'
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Setup XCode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Setup PyOxidizer and build
      working-directory: client/
      run: |
        wget ${PYOXIDIZER_DOWNLOAD}
        unzip pyoxidizer-0.18.0-macos-universal.zip
        sudo chmod +x ./macos-universal/pyoxidizer
        ./macos-universal/pyoxidizer build exe --release
        cp `find build/ -name "gefyra"` ../gefyra
        cp README.md ../README.md
        cat pyproject.toml | grep version -m 1 | awk '{ print "APP_VERSION="substr($3, 2, length($3) -2)}' >> $GITHUB_ENV
   
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gefyra-xx-darwin-amd64
        path: |
          gefyra
          LICENSE
          README.md
        retention-days: 5
    - name: Create release zip
      if: ${{ github.event.release && github.event.action == 'published' }}
      run: zip gefyra-xx-darwin-amd64.zip "gefyra" "LICENSE" "README.md"
    - name: Attach files to release
      uses: softprops/action-gh-release@v1
      if: ${{ github.event.release && github.event.action == 'published' }}
      with:
        files: gefyra-xx-darwin-amd64.zip
